theme:
  name: material

site_name: 虚拟货币模拟盘交易记录
site_description: 个人虚拟货币模拟盘交易记录和分析
copyright: 2026 虚拟货币模拟盘交易记录

nav:
  - 首页: index.md
  - Record:
    - Day 1: record/day1.md
    - Day 2: record/day2.md
    - Day 3: record/day3.md
    - Day 4: record/day4.md
    - Day 5: record/day5.md
    - Day 6: record/day6.md
    - Day 7: record/day7.md
    - Day 8: record/day8.md
    - Day 9: record/day9.md
    - Day 10: record/day10.md
    - Day 11: record/day11.md
    - Day 12: record/day12.md
    - Day 13: record/day13.md
    - Day 14: record/day14.md
    - Day 15: record/day15.md
    - Day 16: record/day16.md
    - Day 17: record/day17.md
    - Day 18: record/day18.md
    - Day 19: record/day19.md
    - Day 20: record/day20.md
    - Day 21: record/day21.md
    - Day 22: record/day22.md
    - Day 23: record/day23.md
    - Day 24: record/day24.md
    - Day 25: record/day25.md
    - Day 26: record/day26.md
    - Day 27: record/day27.md
    - Day 28: record/day28.md
    - Day 29: record/day29.md
    - Day 30: record/day30.md
    - Day 31: record/day31.md
    - Day 32: record/day32.md
    - Day 33: record/day33.md
    - Day 34: record/day34.md
    - Day 35: record/day35.md
    - Day 36: record/day36.md
    - Day 37: record/day37.md
    - Day 38: record/day38.md
    - Day 39: record/day39.md
    - Day 40: record/day40.md
    - Day 41: record/day41.md
    - Day 42: record/day42.md
    - Day 43: record/day43.md
    - Day 44: record/day44.md
    - Day 45: record/day45.md
    - Day 46: record/day46.md
    - Day 47: record/day47.md
    - Day 48: record/day48.md
    - Day 49: record/day49.md
    - Day 50: record/day50.md
    - Day 51: record/day51.md
    - Day 52: record/day52.md
    - Day 53: record/day53.md
    - Day 54: record/day54.md
    - Day 55: record/day55.md
    - Day 56: record/day56.md
    - Day 57: record/day57.md
    - Day 58: record/day58.md
    - Day 59: record/day59.md
    - Day 60: record/day60.md
    - Day 61: record/day61.md
    - Day 62: record/day62.md
    - Day 63: record/day63.md
    - Day 64: record/day64.md
    - Day 65: record/day65.md
    - Day 66: record/day66.md
    - Day 67: record/day67.md
    - Day 68: record/day68.md
    - Day 69: record/day69.md
    - Day 70: record/day70.md
    - Day 71: record/day71.md
    - Day 72: record/day72.md
    - Day 73: record/day73.md
    - Day 74: record/day74.md
    - Day 75: record/day75.md
    - Day 76: record/day76.md
    - Day 77: record/day77.md
    - Day 78: record/day78.md
    - Day 79: record/day79.md
    - Day 80: record/day80.md
    - Day 81: record/day81.md
    - Day 82: record/day82.md
    - Day 83: record/day83.md
    - Day 84: record/day84.md
    - Day 85: record/day85.md
    - Day 86: record/day86.md
    - Day 87: record/day87.md
    - Day 88: record/day88.md
    - Day 89: record/day89.md
    - Day 90: record/day90.md
    - Day 91: record/day91.md
    - Day 92: record/day92.md
    - Day 93: record/day93.md
    - Day 94: record/day94.md
    - Day 95: record/day95.md
    - Day 96: record/day96.md
    - Day 97: record/day97.md
    - Day 98: record/day98.md
    - Day 99: record/day99.md
    - Day 100: record/day100.md


plugins:
  - search

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SEMHAQ/crypto_simulated_trading

